---
language: node_js

sudo: false

cache:
  directories:
    - node_modules

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - node

before_install:
  - "npm config set spin false"

install:
  - time npm install

before_script:
  - npm install -g broccoli-cli

script:
  - npm test
